version: 2

jobs:
  build:
    docker:
      - image: person142/latex:latest
    steps:
      - checkout
      - run: |
          apt-get install -y texlive-science
          mkdir /papers/artifacts
          cd scipy-1.0
          make
          cp paper.pdf /papers/artifacts
      - store_artifacts:
          path: /papers/artifacts
